version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:user
      POSTGRES_PASSWORD:password
      POSTGRES_DB:urls
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      -db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/urls
    ports:
      - "8000:8000"
      